---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
    type: pod
spec:
  containers:
    - name: mysql
      image: mysql:latest
      ports:
        - containerPort: 3306
      envFrom:
        - secretRef:
            name: mysql-sec