apiVersion: v1
kind: Pod
metadata: 
  name: exec3
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: alpine
      image: alpine:3.18
      args: 
        - sleep
        - 1d
    - name: alpine
      image: alpine:3.18
      args: 
        - sleep
        - 10s