---
apiVersion: batch/v1
kind: CronJob
metadata: 
  name: crojb-1
  labels:
    app: nginx
spec:
  schedule: '* * * * *'
  jobTemplate:
    metadata: 
      name: CronJob
      labels:
        app: nginx
    spec:
      backoffLimit: 3
      template:
        metadata: 
          name: crojb-1
          labels:
            app: nginx
        spec:
          restartPolicy: OnFailure
          containers:
            - name: nginx
              image: nginx:1.23
              ports:
                - containerPort: 80
              livenessProbe:
                httpGet:
                  path: /
                  port: 80
              readinessProbe:
                httpGet:
                  path: /
                  port: 80
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "250m"
                limits:
                  memory: "256Mi"
                  cpu: "1000m"
