---
apiVersion: v1
kind: Pod
metadata: 
  name: exec4
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: httpd
      image: httpd:latest
      ports:
        - containerPort: 80
