---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica
spec:
  minReadySeconds: 1
  replicas: 1
  selector:
    matchLabels:
      app: gameoflife
  template:
    metadata:
      name: replicapod
      labels: 
        app: gameoflife
    spec:
      containers:
         - name: gameoflife 
           image: docker push 985724238893.dkr.ecr.ap-south-1.amazonaws.com/somanath:latest
           ports:
             - containerPort: 28000




