---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-config-env
spec:
  containers:
    - name: alpine
      image: alpine
      args:
        - sleep
        - 1d
      envFrom:
        - configMapRef:
            name: dummy-cm
            optional: false
          

