---
apiVersion: v1
kind: Pod
metadata:
  name: alpinepod
  labels: 
    name: alpine
spec:
  containers:
    - name: alpine
      image: alpine:3.18
      command:
        - sleep
        - 1d
      

