---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins
spec:
  minReadySeconds: 2
  replicas: 5
  selector:
    matchLabels:
      app:
  template:
    metadata:
      name: jenikns
      labels:
        app: jenikns
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
        - name: alpine
          image: alpine:3.18
          command:
            - sleep
            - 1d