---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica
  labels:
spec:
  minReadySeconds: 1
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: replicapod
      labels: 
        app: nginx
    spec:
      containers:
         - name: nginx 
           image: nginx:1
           ports:
             - containerPort: 80




