---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  annotations:
    kubernetes.io/change-cause: "update to debian 2"
  labels:
    app: fluentd
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata: 
      name: fluentd
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: fluentd:v1.16.0-debian-1.0
   
