---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: nginx-s
  labels:
    app: nginx
spec:
  minReadySeconds: 5
  serviceName: nginx-svc
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels: 
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - containerPort: 80
          volumeMounts:
            - name: htmlhome
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: htmlhome
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard-rwx